In [1]:
import numpy as np
import re
import nltk

In [2]:
from sklearn.datasets import load_files
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading wordnet: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


In [3]:
feedback_data = load_files(r"C:\Data science\feedbacks")

In [4]:
X, y = feedback_data.data, feedback_data.target

In [5]:
documents = []

from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

In [6]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

In [7]:
for sen in range(0, len(X)):
     # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
     # Converting to Lowercase
    document = str(document).lower()
    
    # Lemmatization
    document = document.split()
    
    document = [stemmer.lemmatize(word) for word in document]
    
    document = [ps.stem(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(max_features=8, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = tfidfconverter.fit_transform(documents).toarray()

from sklearn.feature_extraction.text import CountVectorizer
#list of text documents
text = ["The quick brown fox jumped over the lazy dog."]
#create the transform
vectorizer = CountVectorizer()
#tokenize and build vocab
vectorizer.fit(text)
#summarize
print(vectorizer.vocabulary_)
#encode document
vector = vectorizer.transform(text)
#summarize encoded vector
print(vector.shape)
print(type(vector))
print(vector.toarray())

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 , random_state=0)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
model = KNeighborsClassifier(n_neighbors=3)

In [12]:
#clf = KNeighborsClassifier().fit(X, twenty_train.target)
print(y)

[0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1 0 0 1 1 0]


In [13]:
clf = KNeighborsClassifier().fit(X_train, y_train)

In [14]:
y_pred = clf.predict(X_test)
print(y_pred)

[0 1 0 0 0 1 1 1 1]


In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[4 0]
 [0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         5

    accuracy                           1.00         9
   macro avg       1.00      1.00      1.00         9
weighted avg       1.00      1.00      1.00         9

1.0


In [16]:
nltk.__version__

'3.6.5'