In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
dataset = pd.read_csv('C:\\Users\\HP\\python\\DecisionTree\\maharashtrian.csv')
x = dataset.iloc[:, [ 1,2,3,4]].values
y = dataset.iloc[:, -1].values
print(x)

[[21  0  1  1]
 [22  1  1  0]
 [28  1  1  0]
 [25  0  0  1]
 [30  1  1  1]
 [32  1  0  0]
 [27  1  1  0]
 [24  1  1  0]
 [23  1  1  0]
 [33  1  0  1]
 [40  1  0  0]
 [25  1  1  1]
 [20  0  1  0]
 [23  1  0  0]
 [35  0  0  1]]


In [3]:
print(y)

[1 1 1 0 1 1 1 1 0 0 1 0 1 1 0]


In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.20, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [8]:
y_pred = classifier.predict(x_test)

In [9]:
y_pred

array([1, 1, 1], dtype=int64)

In [10]:
y_test

array([1, 1, 0], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [12]:
ac

0.6666666666666666

In [13]:
cm

array([[0, 1],
       [0, 2]], dtype=int64)

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state = 0)

In [21]:
y_pred = classifier.predict(x_test)

In [22]:
y_pred

array([1, 1, 1, 1, 1], dtype=int64)

In [23]:
y_test

array([1, 1, 0, 0, 0], dtype=int64)

In [24]:
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

In [25]:
cm

array([[0, 3],
       [0, 2]], dtype=int64)

In [26]:
ac

0.4